### ISSUE TITLE
Need to document (add tooltip) about the data directory structure

### ISSUE THREAD

**Issue by hasindu2008** [Psy-Fer/interARTIC#38]
When I put the data directory as:

ebola/fastq_pass
ebola/fast5_pass

It got confused:
![image](https://user-images.githubusercontent.com/12987163/115106410-fe50e000-9fa7-11eb-837f-183cbb5398e4.png)

When it is as below, it is fine:
ebola/runid/fastq_pass
ebola/runid/fast5_pass

**Comment by Psy-Fer** [comment]
fixed in 5974abc9b46fd725f0c8a731f02191b89663a585 and 91da7094575a411de3025ff5ca424cfa3497e135

**Comment by hasindu2008** [comment]
I think the proper names:
        sample_id and run_uuid
