### ISSUE TITLE
After a job failed, rerunning option gives error

### ISSUE THREAD

**Issue by hasindu2008** [Psy-Fer/interARTIC#41]
![image](https://user-images.githubusercontent.com/12987163/115176625-ce711c00-a110-11eb-9a4f-1fb974d44b23.png)

![image](https://user-images.githubusercontent.com/12987163/115176549-ad103000-a110-11eb-9207-b28aa1797d5f.png)

**Comment by Psy-Fer** [comment]
I think the best solution for this, for now, is to just disable this portion of the workflow, as it got rather complex with the large amount of development done, and many things fell through the cracks for how this is managed.
