### ISSUE TITLE
Button for "next" and "download all"

### ISSUE THREAD

**Issue by hasindu2008** [Psy-Fer/interARTIC#45]
It would be nice to have a "next" and "back" button to go through samples in a run, and also a button to download a tarball containing all final consensus fastas.

**Comment by hanfan1803** [comment]
@hasindu2008 when running ONT flowcell with 96 barcoding kit, the option to get all consensus sequences in a directory would help. This directory will be as input for covid mutation classification like https://pangolin.cog-uk.io/ and nextstrain. This option could save a lot of time.

**Comment by Psy-Fer** [comment]
I should also move this button to the top.

**Comment by Psy-Fer** [comment]
- [ ] Download all as zip
- [ ] Download all as single fasta
- [ ] Next/Previous nav buttons
- [ ] Move nav and download buttons to top

**Comment by Psy-Fer** [comment]
Will move buttons when re-organising output page

**Comment by Psy-Fer** [comment]
Buttons moved.
