### ISSUE TITLE
Add version info to web interface

### ISSUE THREAD

**Issue by Psy-Fer** [Psy-Fer/interARTIC#51]
Add a static/prominant version stamp to all pages.

Probably just add it to the page template, and link to a global var in main.py

**Comment by Psy-Fer** [comment]
Added Version of InterARTIC and ARTIC to bottom of every page.

Need to add more granular version of all software used by ARTIC in about page. This will also help as an ENV check

**Comment by Psy-Fer** [comment]
Added versions on about page in commit https://github.com/Psy-Fer/interARTIC/commit/73e809df6665eaae105481f8b4db67aa937dbe98

**Comment by Psy-Fer** [comment]
Because the version checks are run in the celery env, and all tasks are currently set to run serially, the env version checks try to wait for any currently running jobs in the queue before it runs.

I need to figure out how to force the about check to run asynchronously, even if it's in serial mode.

**Comment by Psy-Fer** [comment]
So this issue comes down to the fact that we need one of the celery workers to run a task so that we can access the version info of the software they use when running the jobs.

However, because we use `--concurrency=1` in our run.sh script when launching celery, this makes all the tasks serial, rather than asynchronous. 

So this means, while no jobs are running, the about page will run fine with the version check.
But once a job starts, it goes into the queue, and won't load till after the job is finished.

If I change that to `--concurrency=2`, then while a job is running, the about page and version loading works fine, as it will allow 2 tasks to asynchronously run.

However, if the user launches a medaka and nanopolish (both) run, or multiple runs, this will run everything asynchronously, potentially using more resources than it can handle. But also, it needs a 3rd slot for the about page to run, as the 2 allowed slots for concurrency are taken up.

I'm not really sure how to get around this, other than to either fully remove the block on concurrency, and add some kind of rate limiter in the code. Seems a bit excessive for some version checks. 

So instead, I will run the version check at the start of the app. Then if there are no tasks running, I will run it again. But if there is a task running, I will use the original version check from the start and skip the function call.

Hopefully, this is good enough for most cases, as people shouldn't really be troubleshooting versions while tasks are running anyway.

**Comment by Psy-Fer** [comment]
okay, instead of the check at the start, every time versions about is selected, it makes a version file. if there are tasks running, it reads this file instead of trying to build it again. if there are no tasks running, it builds it from scratch.

The only time this would fail, is the FIRST time this is run, if the user starts a task, then hits about. 

fix in:
https://github.com/Psy-Fer/interARTIC/commit/94f96e65212b1322d968aaacd4f52eb26556ab14

**Comment by hasindu2008** [comment]
works
