### ISSUE TITLE
Add html docs pages to app

### ISSUE THREAD

**Issue by Psy-Fer** [Psy-Fer/interARTIC#52]
Get html renders and add help/docs links to page template.

Test it doesn't break workflows.

**Comment by Psy-Fer** [comment]
to make it not require the index.html file and work offline, a version with this flag in the yaml file needs to be created.

`use_directory_urls: false`

https://github.com/mkdocs/mkdocs/issues/1498

**Comment by Psy-Fer** [comment]
Alright, added in https://github.com/Psy-Fer/interARTIC/commit/7823360b775180a9f462ff76137fb1f4839d48b5

**Comment by hasindu2008** [comment]
works!
