### ISSUE TITLE
utf-8 compatibility

### ISSUE THREAD

**Issue by Psy-Fer** [Psy-Fer/interARTIC#55]
Make paths, filenames, etc to be utf8 compatible to be more flexible.

@Psy-Fer to do snake side

@hasindu2008 to do bash side

**Comment by Psy-Fer** [comment]
Also look at glob/or whatever to be file system agnostic

**Comment by Psy-Fer** [comment]
okay, went for a more dirty approach. I have manually set what is not allowed. It's not perfect but will stop 99% of issues.

https://github.com/Psy-Fer/interARTIC/commit/0b2a9337edb2c10e29a65e34832da09beeac0008

**Comment by hasindu2008** [comment]
works!
