### ISSUE TITLE
Can the abort button be hiddenor show something in green like success after all steps complete?

### ISSUE THREAD

**Issue by hasindu2008** [Psy-Fer/interARTIC#59]
When a job completes, the abort button becomes bigger than before and this may mislead someone to think that the job failed. 

before:
![image](https://user-images.githubusercontent.com/12987163/130460101-e9b5d22b-a151-47f1-990d-8ba09bdfb2d6.png)

after:
![image](https://user-images.githubusercontent.com/12987163/130459884-4a86155f-151c-4e3a-bf5d-a55e8383990b.png)

**Comment by Psy-Fer** [comment]
Something weird about the button becoming bigger, but as a way around this, I've changed it to be "success" when no errors are detected.

![image](https://user-images.githubusercontent.com/8985577/131492226-99b8b3b5-a779-4b4e-88f5-088f028a038d.png)

**Comment by Psy-Fer** [comment]
okay, i had the logic around the wrong way. This should work now. I tested with a fresh run (no errors) and a dodgy run (with errors) and it looks the way it should.

https://github.com/Psy-Fer/interARTIC/commit/d66b8b235846a03259cfc0d55d14f30f5fb7c20d

**Comment by hasindu2008** [comment]
works
