### ISSUE TITLE
More QC metrics on output

### ISSUE THREAD

**Issue by Psy-Fer** [Psy-Fer/interARTIC#60]
Add in extra QC metrics for each sample, displayed in copy/paste compliant table, as well as add buttons to download sample as well as all samples in a tsv file.

**Comment by Psy-Fer** [comment]
The bulk of this is done. Needs to be reviewed.

**Comment by Psy-Fer** [comment]
Need to alter how variant depth is calculated. Charles at PoW raised a good point about this calculation, and how the current VCFs produced by ARTIC are.....not great. I'll do my best effort for the plots and table, as an indicator to the user, but this kind of in-depth analysis should be handled outside of InterARTIC/ARTIC as it currently is by the users we have encountered.

**Comment by Psy-Fer** [comment]
Okay, this is now fixed in both the QC tables and CoVar Plots.

**Comment by hasindu2008** [comment]
Looks good to me! WIll close the issue for now.
