### ISSUE TITLE
fix input for single sample when compiling metadata for QC report

### ISSUE THREAD

**Issue by Psy-Fer** [Psy-Fer/interARTIC#63]
When a single sample (selected on parameters page), fastq file isn't moved to it's own folder, and thus the fastq cannot be found for metadata QC report generation. Best way to solve this is to run single sample runs similar to multi, and still move the files.

**Comment by Psy-Fer** [comment]
This should be fixed now

**Comment by Psy-Fer** [comment]
okay, i got the relative directory wrong. this is fixed now.

**Comment by hasindu2008** [comment]
works!
