### ISSUE TITLE
macOS library's missing?

### ISSUE THREAD

**Issue by Psy-Fer** [Psy-Fer/interARTIC#64]
dyld: Library not loaded: /Users/gtg/miniconda3/envs/artic-ncov2019/lib/libtinfow.6.dylib
  Referenced from: /Users/iradeveson/Desktop/interartic_bin/artic_bin/lib/libncursesw.6.dylib
  Reason: image not found
dyld: Library not loaded: /Users/gtg/miniconda3/envs/artic-ncov2019/lib/libtinfow.6.dylib
  Referenced from: /Users/iradeveson/Desktop/interartic_bin/artic_bin/lib/libncursesw.6.dylib
  Reason: image not found

missing libraries on macOS?

**Comment by hasindu2008** [comment]
It is a mistake when creating the tarball - mistakenly used an older version I believe.

**Comment by hasindu2008** [comment]
Tested on the gtg macbook and worked
